server:
  port: 8090
  servlet:
    context-path: /meeting

spring:
  # 配置数据源
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false

mybatis-plus:
  mapper-locations: classpath:com/canway/manager/dao*.xml
  type-aliases-package: com.canway.manager.pojo
  configuration:
    map-underscore-to-camel-case: true

